openapi: 3.0.0
info:
  title: Benchmarketing API
  version: 1.0.0
paths:
  /api/search:
    get:
      operationId: searchContent
      summary: Buscar conteúdos técnicos sobre tráfego pago
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de conteúdos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
